### ISSUE TITLE
bg

### ISSUE THREAD

**Issue by arinjain373** [arinjain373/The-Simon-Game#1]
Change the background colour

**Comment by deepesh16b** [comment]
Please assign this to me
@arinjain373 
I can change the background

**Comment by Kanishk-Dukia** [comment]
please assgin this to me.
thank you

**Comment by arinjain373** [comment]
Start working
@Kanishk-Dukia

**Comment by utsav000** [comment]
please assign me this

**Comment by deepesh16b** [comment]
@arinjain373 
Please review my work

**Comment by arinjain373** [comment]
Done
